book_website/book_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

book_website/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    # детали книги - book_detail
    path('books/<int:id>/', views.book_detail, name='book_detail'),
    # книги - books
    path('books', views.books, name='books'),
    # редактирование книги - book_edit
    path('books/<int:id>/edit/', views.book_edit, name='book_edit'),
    # удаление книги - book_delete
    path('books/<int:id>/delete', views.book_delete, name='book_delete'),
    # создание книги - book_create
    path('book_create/', views.book_create, name='book_create'),
    # поиск книги - search_book
    path('search_book/', views.search_book, name='search_book'),
    # поиск избранной книги - search_favorite_book
    path('search_favorite_book/', views.search_favorite_book,
         name='search_favorite_book'),
    # рекомендации для книги - book_recommend
    path('book_recommend/<int:id>', views.book_recommend,
         name='book_recommend'),
    # рекомендации - recommendations
    path('recommendations', views.recommendations, name='recommendations'),

    # избранные книги - favorites
    path('favorites/', views.favorites, name='favorites'),
    # добавление книги в избранное - make_favore
    path('make_favore/<int:id>/', views.make_favore, name='make_favore'),
    # удаление книги из избранное - make_not_favore
    path('make_not_favore/<int:id>/', views.make_not_favore,
         name='make_not_favore'),

    # добавление комментария - add_comment
    path('books/<int:id>/comment/', views.add_comment, name='add_comment'),
    # удаление комментария - delete_comment
    path('books/<int:id>/comment/<int:comment_id>/delete',
         views.delete_comment, name='delete_comment'),

    # автор - author_detail
    path('/authors/<int:id>/', views.author_detail, name='author_detail'),
    # авторы - authors
    path('authors/', views.authors, name='authors'),
    # редактирование автора - author_edit
    path('/authors/<int:id>/edit/', views.author_edit, name='author_edit'),
    # добавление автора - author_create
    path('author_create/', views.author_create, name='author_create'),
    # удаление автора - author_delete
    path('/authors/<int:id>/delete', views.author_delete, name='author_delete'),
    # поиск автора - search_author
    path('search_author/', views.search_author, name='search_author'),

    # объект не найден - object_not_found
    path('object_not_found/', views.object_not_found, name='object_not_found'),

    path('section_create/', views.section_create, name='section_create'),
]

book_website/books/forms.py
from django import forms

from .models import Book, Author, Comment, Section


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ('name',)
        labels = {'name': 'Название секции'}


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        section = forms.ModelChoiceField(queryset=Section.objects.all(),
                                       required=False)
        fields = ('name', 'section_id', 'publish', 'age', 'year',
                  'pages', 'description', 'author_id', 'image')


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('author_name', 'photo')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст комментария'}
        help_texts = {'text': 'Введите текст комментария'}

book_website/books/views.py
import re

import nltk
import pandas as pd
import spacy
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer

from .forms import BookForm, AuthorForm, CommentForm, SectionForm
from .models import Book, Author, Comment, FavoreBook
from .recommendations import recommend


def index(request):
    """Главная страница."""

    template = 'index.html'
    return render(request, template)


def get_favore_flags(request):
    """Отображение избранных книг."""

    favore_flags = []
    if request.user.is_authenticated:
        # все избранные книги для данного пользователя
        favore_books = FavoreBook.objects.filter(person=request.user)
        # если книга в избранном, добавляем ее id в список
        for favorite in favore_books:
            favore_flags.append(favorite.book.id)
    else:
        # для неавторизованных пользователей избранные книги недоступны
        favore_books = []
    return favore_books, favore_flags


def books(request):
    """Страница со списком книг."""

    template = 'books/books.html'
    books_objects = Book.objects.order_by('-year')
    book_list = Book.objects.all()
    paginator = Paginator(book_list, 64)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    favore_books, favore_flags = get_favore_flags(request)

    context = {
        'title': 'Books',
        'books': books_objects,
        'page_obj': page_obj,
        'favore_books': favore_books,
        'favore_flags': favore_flags
    }
    return render(request, template, context)


def book_detail(request, id):
    """Детали о книге."""
    template = 'books/book_detail.html'
    books_objects = get_object_or_404(Book, id=id)
    form = CommentForm(request.POST or None)
    favore_books, favore_flags = get_favore_flags(request)

    context = {
        'book': books_objects,
        'form': form,
        'comments': books_objects.comments.all(),
        'favore_flags': favore_flags
    }
    return render(request, template, context)


@login_required
def recommendations(request):
    """Страница рекомендаций."""

    template = 'recommendations.html'
    context = {
        'title': 'Recommendations',
    }
    return render(request, template, context)


def book_recommend(request, id, for_recommend=False):
    """Вывод рекомендаций к выбранной книге."""

    try:
        if not for_recommend:
            for_recommend = Book.objects.filter(id=id)
        for_recommend_name = for_recommend[0].name
        books_rec_list = []
        recommend_books = recommend(for_recommend_name)
        for book_name in recommend_books:
            if Book.objects.filter(name__icontains=book_name.strip()):
                books_rec_list.append(Book.objects.filter(name__icontains=
                                                          book_name.strip()))
        test = books_rec_list[0]
        for book in books_rec_list[1:]:
            test = test | book
        paginator = Paginator(test, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'title': 'Books',
            'books': test,
            'page_obj': page_obj,
            'book_name': for_recommend_name
        }
        return render(request, 'recommendations.html', context)
    except:
        return redirect('books:object_not_found')


@login_required
def make_favore(request, id):
    """Добавить книгу в избранное."""
    FavoreBook.objects.get_or_create(person=request.user,
                                     book=get_object_or_404(Book, id=id))
    return redirect('books:favorites')


@login_required
def make_not_favore(request, id):
    """Удалить книгу из избранного."""
    FavoreBook.objects.filter(person=request.user,
                              book=get_object_or_404(Book, id=id)).delete()
    return redirect('books:books')


@login_required
def favorites(request):
    """Избранное."""

    template = 'books/favorites.html'
    books_objects = FavoreBook.objects.filter(person=request.user)
    paginator = Paginator(books_objects, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'books': books_objects,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# region add_tags
def stopslova(text):
    """Удаляет стоп-слова и возвращает текст без них."""

    y = []
    stop_words = stopwords.words('russian')
    for i in text.split():
        if not i in stop_words:
            y.append(i)
    return " ".join(y)


def spacylem(text):
    """Обработка текста через spacy."""

    nlp = spacy.load('ru_core_news_sm')
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc]
    return " ".join(tokens)


def stemming(text):
    """Стемминг - отрезание окончаний слов."""

    stemmer = SnowballStemmer(language='russian')
    tokenizer = nltk.tokenize.WhitespaceTokenizer()
    tokens = [stemmer.stem(w) for w in tokenizer.tokenize(text)]
    return " ".join(tokens)


def tags_create(description, section):
    """Создание тегов из описаний книг."""

    description = re.sub("[^А-Яа-я, ё, \n, -]", "", description)
    description = description.lower()
    description = re.sub(",", " ", description)
    description = re.sub("\n", " ", description)
    description = re.sub("-", " ", description)
    description_without_stopwords = stopslova(description)
    description_spacy = spacylem(description_without_stopwords)
    description_stemming = stemming(description_spacy)
    return description_stemming + section
# endregion


def vector_add(name, tag):
    """Добавление вектора по тегам в базу при добавлении новой книги."""

    cv = CountVectorizer(encoding='utf-8')
    data = pd.read_csv('/Users/dianaverevkina/Diplom_project/'
                       'Diploma — копия 3/data_preparation/spacylem.csv')
    data.loc[len(data.index)] = [name, tag]
    data.to_csv(r'/Users/dianaverevkina/Diplom_project/Diploma — копия 3/'
                r'data_preparation/spacylem.csv', index=False)

    cv.fit(data['tags'])
    vectors = cv.fit_transform(data['tags'].values.astype('U'))
    vector = vectors[-1]
    return vector


@login_required
def book_create(request):
    """Добавление новой книги."""

    form = BookForm(request.POST or None, files=request.FILES or None, )
    if not form.is_valid():
        return render(request, 'books/create_book.html', {'form': form})
    book = form.save(commit=False)
    book.tags = tags_create(book.description, book.section)
    book.vector = vector_add(book.name, book.tags)
    book.name_lower = book.name.lower()
    book.save()
    return redirect('books:books')


@login_required
def section_create(request):
    """Добавление новой секции."""
    form = SectionForm(request.POST or None, files=request.FILES or None, )
    if not form.is_valid():
        return render(request, 'books/section_create.html', {'form': form})
    section = form.save(commit=False)
    section.save()
    return redirect('books:books')


@login_required
def book_edit(request, id):
    """Редактирование книги."""

    book = get_object_or_404(Book, id=id)
    form = BookForm(request.POST or None, files=request.FILES or None,
                    instance=book)
    if form.is_valid():
        form.save()
        return redirect('books:book_detail', id)
    return render(request, 'books/create_book.html', {'form': form})


@login_required
def author_edit(request, id):
    """Редактирование автора."""

    author = get_object_or_404(Author, id=id)
    form = AuthorForm(request.POST or None, files=request.FILES or None,
                      instance=author)
    if form.is_valid():
        form.save()
        return redirect('books:author_detail', id)
    return render(request, 'authors/create_author.html', {'form': form})


def author_detail(request, id):
    """Детали об авторе."""

    template = 'authors/author_detail.html'
    author = get_object_or_404(Author, id=id)
    book_list = author.books.distinct()
    context = {
        'author': author,
        'book_list': book_list,
    }
    return render(request, template, context)


@login_required
def author_create(request):
    """Добавление нового автора."""

    form = AuthorForm(request.POST or None, files=request.FILES or None, )
    if not form.is_valid():
        return render(request, 'authors/create_author.html', {'form': form})
    author = form.save(commit=False)
    author.author_name_lower = author.author_name.lower()
    author.save()
    return redirect('books:authors')


def authors(request):
    """Отображение списка авторов."""

    template = 'authors/authors.html'
    author_objects = Author.objects.all()
    author_list = Author.objects.all()
    paginator = Paginator(author_list, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Authors',
        'authors': author_objects,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def book_delete(request, id):
    """Удаление книги."""

    book = get_object_or_404(Book, id=id)
    book.delete()
    return redirect('books:books')


@login_required
def author_delete(request, id):
    """Удаление автора."""

    author = get_object_or_404(Author, id=id)
    author.delete()
    return redirect('books:authors')


@login_required
def add_comment(request, id):
    """Добавление коментария."""

    book = get_object_or_404(Book, id=id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.book = book
        comment.save()

book_website/templates/books/book_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles_bootstrap.css' %}">
{% block title %}
  "Детали"
{% endblock %}

{% block content %}
  <section class="a">
    <div class="container-fluid" style="background: rgba(225,180,148,0.65)">
      <div class="row">
        <div class="col-sm-1 col-lg-1"><p></p></div>

        <div class="col-sm-12 col-lg-12">
          <p id="book_name">{{ book.name }}</p>
        </div>

        <div class="col-sm-4 col-lg-4 shadow-sm">
          <div class="col">
            <div class="card h-100">
              {% if book.cove %}
                <img src="{{ book.cove }}" class="card-img-top" alt="...">
              {% else %}
                {% thumbnail book.image "960x339" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
              {% endif %}

            </div>
          </div>
        </div>

        <div class="col-sm-8 col-lg-8" id="book_description">
        <a style="color: #1c65d3"
               href="{{book.shop}}">
            Ссылка на магазин </a>
        <p></p>
          {% if book.author_id %}
            <p>Автор: <small><a id="book_link"
                                 href="{% url 'books:author_detail' book.author_id.id %}">{{ book.author_id.author_name }}</a>
            </small></p>
          {% else %}
            <p style="color: #641010"> Автор неизвестен </p>
          {% endif %}
          <p>Секция: <small> {{ book.section }} </small></p>
          <p>Возрастное ограничение: <small> {{ book.age }} </small></p>
          <p>Год издания: <small> {{ book.year }} </small></p>
          <p>Количество страниц: <small> {{ book.pages }} </small></p>
          <p>Описание: <small> {{ book.description }} </small></p>
          {% if user.username == 'dianaverevkina' %}
            <a class="btn btn-primary"
               style="background: #c79577; border-color: #8a5834"
               href="{% url 'books:book_edit' id=book.id %}">
            редактировать запись
            <a class="btn btn-primary"
               href="{% url 'books:book_delete' id=book.id %}"
               style="background: darkred; border-color: #641010">
              удалить запись
            </a>
          {% else %}
            <span style='color: darkred'> редактирование недоступно </span>
          {% endif %}
          {% if book.id in favore_flags %}
            <a id="book_link" href="{% url 'books:make_not_favore' book.id %}
            " style="font-size: 20pt; color: darkred">&#9829;</a>
          {% else %}
            <a id="book_link" href="{% url 'books:make_favore' book.id %}
            " style="font-size: 20pt; color: darkred">&#9825;</a>
          {% endif %}
        <p></p>
                  <a style="color: #411910" id="book_link" href="{% url 'books:book_recommend' book.id %}">посмотреть похожие</a>

        </div>

        <div class="col-sm-12 col-lg-12">
          {% include "includes/add_comment.html" %}
          <p></p>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

book_website/templates/books/books.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  "Книги"
{% endblock %}

{% block content %}
  <section class="a" style="background: rgba(225,180,148,0.65)">
    <div class="container-fluid">
      <div class="row">
        <p></p>
        <form action="{% url 'books:search_book' %}" method="get">
          <input name="q" type="text" placeholder="Поиск...">
          <button type="submit" class="btn btn-primary"
                  style="background: #72513e; border-color: #41220c">
            Найти
          </button>
        </form>
        {% include "includes/books_objects.html" %}
      </div>
    </div>
    {% include 'includes/paginator.html' %}
    <p style="color: rgba(225,180,148,0.65)">-</p>
  </section>

{% endblock %}

book_website/templates/books/create_book.html
{% extends "base.html" %}
{% block title %}
  Добавление книги
{% endblock %}

{% block content %}
  <div class="container-fluid" style="background: rgba(225,180,148,0.65)">
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
            {% if form.instance.pk %} Редактировать книгу
            {% else %} Добавить книгу {% endif %}
          </div>
          <div class="card-body" style="background: rgba(255,235,213,0.53)">
            {% include "includes/block_errors.html" %}
            <form method="post" enctype="multipart/form-data"
                  {% if form.instance.pk %}
                      action="{% url 'books:book_edit' form.instance.pk %}"
                    {% else %}
                      action="{% url 'books:book_create' %}" {% endif %}>
              {% csrf_token %}
              {% include "includes/form.html" %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary"  style="background: #72513e">
                  {% if form.instance.pk %} Сохранить
                  {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

book_website/templates/books/favorites.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  "Избранное"
{% endblock %}

{% block content %}
  <section class="a" style="background: rgba(225,180,148,0.65)">
    <div class="container-fluid">
      <div class="row">
        <p></p>
        <h2 style="color: #6a3f27; text-align: center">Избранные книги</h2>

        <form action="{% url 'books:search_favorite_book'%}" method="get" style="margin-top: -3%">
          <input name="q" type="text" placeholder="Поиск...">
          <button type="submit" class="btn btn-primary"
                style="background: #72513e; border-color: #41220c">
          Найти
        </button>
        </form>

         {% include "includes/books_objects_FAVORITES.html" %}
      </div>
    </div>
    {% include 'includes/paginator.html' %}
    <p style="color: rgba(225,180,148,0.65)">-</p>
  </section>

{% endblock %}

book_website/templates/books/make_favore.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  "Добавлена в избранное"
{% endblock %}

{% block content %}
  <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
            Книга добавлена в избранное
          </div>
          <div class="card-body" style="background: rgba(255,235,213,0.53)">
            <p>Книга '{{ book.name }}' добавлена в избранное</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>

    </p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
    </div> <!-- row -->

{% endblock %}

book_website/templates/books/make_not_favore.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  "Удалена из избранного"
{% endblock %}

{% block content %}
  <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
            Книга удалена из избранного
          </div>
          <div class="card-body" style="background: rgba(255,235,213,0.53)">
            <p>Книга '{{ book.name }}' удалена из избранного</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>

    </p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
    </div> <!-- row -->

{% endblock %}

book_website/templates/books/section_create.html
{% extends "base.html" %}
{% block title %}
  Добавление секции
{% endblock %}

{% block content %}
  <div class="container-fluid" style="background: rgba(225,180,148,0.65)">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header"
                 style="background: #bd9379; color: white; font-weight: bold">
              Добавить секцию
            </div>
            <div class="card-body" style="background: rgba(255,235,213,0.53)">
              {% include "includes/block_errors.html" %}
              <form method="post" enctype="multipart/form-data"

                    action="{% url 'books:section_create' %}">
                {% csrf_token %}
                {% include "includes/form.html" %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary"
                          style="background: #72513e">
                    Добавить
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}