book_website/book_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

book_website/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    # детали книги - book_detail
    path('books/<int:id>/', views.book_detail, name='book_detail'),
    # книги - books
    path('books', views.books, name='books'),
    # редактирование книги - book_edit
    path('books/<int:id>/edit/', views.book_edit, name='book_edit'),
    # удаление книги - book_delete
    path('books/<int:id>/delete', views.book_delete, name='book_delete'),
    # создание книги - book_create
    path('book_create/', views.book_create, name='book_create'),
    # поиск книги - search_book
    path('search_book/', views.search_book, name='search_book'),
    # поиск избранной книги - search_favorite_book
    path('search_favorite_book/', views.search_favorite_book,
         name='search_favorite_book'),
    # рекомендации для книги - book_recommend
    path('book_recommend/<int:id>', views.book_recommend,
         name='book_recommend'),
    # рекомендации - recommendations
    path('recommendations', views.recommendations, name='recommendations'),

    # избранные книги - favorites
    path('favorites/', views.favorites, name='favorites'),
    # добавление книги в избранное - make_favore
    path('make_favore/<int:id>/', views.make_favore, name='make_favore'),
    # удаление книги из избранное - make_not_favore
    path('make_not_favore/<int:id>/', views.make_not_favore,
         name='make_not_favore'),

    # добавление комментария - add_comment
    path('books/<int:id>/comment/', views.add_comment, name='add_comment'),
    # удаление комментария - delete_comment
    path('books/<int:id>/comment/<int:comment_id>/delete',
         views.delete_comment, name='delete_comment'),

    # автор - author_detail
    path('/authors/<int:id>/', views.author_detail, name='author_detail'),
    # авторы - authors
    path('authors/', views.authors, name='authors'),
    # редактирование автора - author_edit
    path('/authors/<int:id>/edit/', views.author_edit, name='author_edit'),
    # добавление автора - author_create
    path('author_create/', views.author_create, name='author_create'),
    # удаление автора - author_delete
    path('/authors/<int:id>/delete', views.author_delete, name='author_delete'),
    # поиск автора - search_author
    path('search_author/', views.search_author, name='search_author'),

    # объект не найден - object_not_found
    path('object_not_found/', views.object_not_found, name='object_not_found'),

    path('section_create/', views.section_create, name='section_create'),
]

book_website/users/urls.py
from django.contrib.auth.views import (
    LogoutView, LoginView, PasswordResetView, PasswordResetDoneView,
    PasswordChangeView, PasswordChangeDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, reverse_lazy
from . import views


app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset_form'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')
    ),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ),
         name='password_change_done'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.
         as_view(template_name='users/password_reset_confirm.html',
                 success_url=reverse_lazy('users:password_reset_complete'), ),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
]

book_website/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

book_website/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('books:index')

book_website/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <p></p>
  <p></p>
  <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
    <div class="col-md-4 p-5">
      <div class="card">
        <h5 class="card-header" style="background: #bd9379; color: white; font-weight: bold">Выход</h5>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">
          <h5 class="card-title"></h5>
          <p class="card-text">Вы вышли из системы.</p>
          <!-- <a href="#" class="btn btn-primary">Перейти куда-нибудь</a> !-->
        </div>
      </div>
    </div>
  <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
  <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
  </div>
{% endblock %}

book_website/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
          Войти на сайт
        </div>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary" style="background: #72513e">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
  <p></p>
</div> <!-- row -->
{% endblock %}

book_website/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  {% load user_filters %}

  <div class="row justify-content-center"
       style="background: rgba(225,180,148,0.85)">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"
             style="background: #bd9379; color: white; font-weight: bold">
          Изменить пароль
        </div>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">

          <form method="post">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row"
                   aria-required={% if field.field.required %}"true"
                   {% else %}"false"{% endif %}>
              <label for="{{ field.id_for_label }}"
                     class="col-md-4 col-form-label text-md-right">
                {{ field.label }}{% if field.field.required %}
                  <span class="required">*</span>{% endif %}</label>
              <div class="col-md-6">
                {{ field|addclass:"form-control" }}

                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help"
                         class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
              </div>
            {% endfor %}
        <p></p>
        <p></p>
        <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary"
                  style="background: #72513e">
            Изменить пароль
          </button>
        </div>
        </form>

      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
  <p></p><p></p><p></p><p></p><p></p><p></p>
  </div> <!-- row -->

{% endblock %}

book_website/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %} "Пароль изменён" {% endblock %}

{% block content %}
    <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
            Пароль изменён
          </div>
          <div class="card-body" style="background: rgba(255,235,213,0.53)">
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>

    </p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>
    </div> <!-- row -->
{% endblock %}

book_website/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля выполнен{% endblock %}

{% block content %}
<div class="row justify-content-center"  style="background: rgba(225,180,148,0.85)">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
        Сброс пароля выполнен</div>
      <div class="card-body" style="background: rgba(255,235,213,0.53)">
        <p>Пароль изменён, всё получилось</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
<p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
</div> <!-- row -->

{% endblock %}

book_website/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% load user_filters %}

  {% if validlink %}

    <div class="row justify-content-center"
         style="background: rgba(225,180,148,0.85)">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header"
               style="background: #bd9379; color: white; font-weight: bold">
            Введите новый пароль
          </div>
          <div class="card-body" style="background: rgba(255,235,213,0.53)">

            <form method="post">
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row"
                     aria-required={% if field.field.required %}"true"
                     {% else %}"false"{% endif %}>
                <label for="{{ field.id_for_label }}"
                       class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}{% if field.field.required %}
                    <span class="required">*</span>{% endif %}</label>
                <div class="col-md-6">
                  {{ field|addclass:"form-control" }}

                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help"
                           class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
                </div>
              {% endfor %}
          <p></p>
          <p></p>
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary"
                    style="background: #72513e">
              Назначить новый пароль
            </button>
          </div>
          </form>

        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    </div> <!-- row -->

  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}

{% endblock %}

book_website/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %} "Сброс пароля прошёл успешно" {% endblock %}

{% block content %}

  <div class="row justify-content-center"
       style="background: rgba(225,180,148,0.85)">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"
             style="background: #bd9379; color: white; font-weight: bold">
          Отправлено письмо
        </div>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для
            восстановления пароля</p>
        </div>
      </div>
    </div>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </div>
{% endblock %}

book_website/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %} "Сброс пароля" {% endblock %}

{% block content %}
  <div class="row justify-content-center"
       style="background: rgba(225,180,148,0.85)">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"
             style="background: #bd9379; color: white; font-weight: bold">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под
          которым вы регистрировались
        </div>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>
              <input type="email" name="email" maxlength="254"
                     class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary"
                      style="background: #72513e">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>

  </div>

{% endblock %}

book_website/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
  <div class="row justify-content-center" style="background: rgba(225,180,148,0.85)">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header" style="background: #bd9379; color: white; font-weight: bold">
          Регистрация
        </div>
        <div class="card-body" style="background: rgba(255,235,213,0.53)">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary" style="background: #72513e">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}