book_website/book_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

book_website/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    # детали книги - book_detail
    path('books/<int:id>/', views.book_detail, name='book_detail'),
    # книги - books
    path('books', views.books, name='books'),
    # редактирование книги - book_edit
    path('books/<int:id>/edit/', views.book_edit, name='book_edit'),
    # удаление книги - book_delete
    path('books/<int:id>/delete', views.book_delete, name='book_delete'),
    # создание книги - book_create
    path('book_create/', views.book_create, name='book_create'),
    # поиск книги - search_book
    path('search_book/', views.search_book, name='search_book'),
    # поиск избранной книги - search_favorite_book
    path('search_favorite_book/', views.search_favorite_book,
         name='search_favorite_book'),
    # рекомендации для книги - book_recommend
    path('book_recommend/<int:id>', views.book_recommend,
         name='book_recommend'),
    # рекомендации - recommendations
    path('recommendations', views.recommendations, name='recommendations'),

    # избранные книги - favorites
    path('favorites/', views.favorites, name='favorites'),
    # добавление книги в избранное - make_favore
    path('make_favore/<int:id>/', views.make_favore, name='make_favore'),
    # удаление книги из избранное - make_not_favore
    path('make_not_favore/<int:id>/', views.make_not_favore,
         name='make_not_favore'),

    # добавление комментария - add_comment
    path('books/<int:id>/comment/', views.add_comment, name='add_comment'),
    # удаление комментария - delete_comment
    path('books/<int:id>/comment/<int:comment_id>/delete',
         views.delete_comment, name='delete_comment'),

    # автор - author_detail
    path('/authors/<int:id>/', views.author_detail, name='author_detail'),
    # авторы - authors
    path('authors/', views.authors, name='authors'),
    # редактирование автора - author_edit
    path('/authors/<int:id>/edit/', views.author_edit, name='author_edit'),
    # добавление автора - author_create
    path('author_create/', views.author_create, name='author_create'),
    # удаление автора - author_delete
    path('/authors/<int:id>/delete', views.author_delete, name='author_delete'),
    # поиск автора - search_author
    path('search_author/', views.search_author, name='search_author'),

    # объект не найден - object_not_found
    path('object_not_found/', views.object_not_found, name='object_not_found'),

    path('section_create/', views.section_create, name='section_create'),
]

book_website/users/urls.py
from django.contrib.auth.views import (
    LogoutView, LoginView, PasswordResetView, PasswordResetDoneView,
    PasswordChangeView, PasswordChangeDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, reverse_lazy
from . import views


app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset_form'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')
    ),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ),
         name='password_change_done'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.
         as_view(template_name='users/password_reset_confirm.html',
                 success_url=reverse_lazy('users:password_reset_complete'), ),
         name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
]

book_website/templates/includes/add_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header"
        style="background: #bd9379; color: white; font-weight: bold">
      Добавить комментарий:</h5>
    <div class="card-body" style="background: rgba(255,235,213,0.53)">
      <form method="post" action="{% url 'books:add_comment' book.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary"
                style="background: #72513e">
          Отправить
        </button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body" style="background: rgba(255,241,222,0.63)">
      <h5 class="mt-0">
        {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text|linebreaksbr }}
      </p>
      {% if user.is_authenticated and comment.author == user or user.username == 'diana'%}
        <a style="color: darkred"
           href="{% url 'books:delete_comment' id=book.id comment_id=comment.id %}">
          удалить комментарий
        </a>
      {% endif %}
    </div>

  </div>
{% endfor %}

book_website/templates/includes/author_objects.html
{% load thumbnail %}
<div class="row row-cols-1 row-cols-md-4 g-4">
  {% for author in page_obj %}
    <div class="col">
      <div class="card h-100">
        {% if author.author_photo %}
          <img src="{{ author.author_photo }}" class="card-img-top" alt="...">
        {% else %}
          {% thumbnail author.photo "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ author.author_name }}</h5>
          <a id="book_link"
             href="{% url 'books:author_detail' author.id %}">подробнее</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

book_website/templates/includes/block_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

book_website/templates/includes/books_objects.html
{% load thumbnail %}

{% if book_name %}
  <p style="color: #4f2a1d; font-size: 16pt; font-weight: bold">Рекомендации к книге "{{ book_name }}"</p>

{% endif %}

<div class="row row-cols-1 row-cols-md-4 g-4">
  {% for book in page_obj %}
    <div class="col">
      <div class="card h-100">
        {% if book.cove %}
          <img src="{{ book.cove }}" class="card-img-top" alt="...">
        {% else %}
          {% thumbnail book.image "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ book.name }}</h5>
          <p class="card-text">{{ book.author }}</p>
          <p class="card-text">{{ book.age }}</p>
          <a id="book_link" href="{% url 'books:book_detail' book.id %}">подробнее</a>
        <p></p>
          <a style="color: #411910" id="book_link" href="{% url 'books:book_recommend' book.id %}">посмотреть похожие</a>
          <p></p>

        {% if book.id in favore_flags %}
          <a id="book_link" href="{% url 'books:make_not_favore' book.id %}
            " style="font-size: 20pt; color: darkred">&#9829;</a>
        {% else %}
          <a id="book_link" href="{% url 'books:make_favore' book.id %}
            " style="font-size: 20pt; color: darkred">&#9825;</a>
         {% endif %}

        </div>
      </div>
    </div>
  {% endfor %}
</div>

book_website/templates/includes/books_objects_FAVORITES.html
{% load thumbnail %}
<div class="row row-cols-1 row-cols-md-4 g-4">
  {% for book in page_obj %}
    <div class="col">
      <div class="card h-100">
        {% if book.book.cove %}
          <img src="{{ book.book.cove }}" class="card-img-top" alt="...">
        {% else %}
          {% thumbnail book.book.image "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ book.book.name }}</h5>
          <p class="card-text">{{ book.book.author }}</p>
          <p class="card-text">{{ book.book.age }}</p>
          <a id="book_link" href="{% url 'books:book_detail' book.book.id %}">подробнее</a>
          <p></p>
            <a id="book_link" href="{% url 'books:make_not_favore' book.book.id %}" style="font-size: 20pt; color: darkred">&#9829;</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

book_website/templates/includes/form.html
{% load user_filters %}

{% for field in form %}
  <div class="form-group row my-3"
          {% if field.field.required %}
            aria-required="true"
          {% else %}
            aria-required="false"
          {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

book_website/templates/includes/header.html
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-7">
      <nav class="navbar navbar-light" style="margin-left: -3%">
        <div class="container">
          <ul class="nav nav-pills">
            {% if user.is_authenticated %}
              <li style="color: #4d3626; margin-top: 8px; background: bisque">
                {{ user.username }}
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'books:book_create' %}"
                   style="color: #4d3626">Новая
                  книга</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'books:author_create' %}"
                   style="color: #4d3626">Новый
                  автор</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'books:section_create' %}"
                   style="color: #4d3626">Новая секция</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light"
                   href="{% url 'users:password_change' %}"
                   style="color: #4d3626">Изменить пароль</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'users:logout' %}"
                   style="color: #4d3626">Выйти</a>
              </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'users:login' %}"
                   style="color: #4d3626">Войти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'users:signup' %}"
                   style="color: #4d3626">Регистрация</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="col-lg-5" style="background: #bd9379">
      <ul id="head_menu">
        <li style="display: inline-block;"><a href="/books">Книги</a></li>
        <li style="display: inline-block; margin-left: 10pt"><a href="/favorites">Избранное</a></li>
        <li style="display: inline-block; margin-left: 10pt"><a href="/authors">Авторы</a></li>
        <li style="display: inline-block; margin-left: 10pt"><a href="/recommendations">Рекомендации</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-2">
    <h1 id="BookFord"><a href="/">BookFord</a></h1>
  </div>
</div>

book_website/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5" style="margin-left: 1%">
    <ul class="pagination" style="margin-top: -2%">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>

          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}