book_website/book_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

book_website/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    # детали книги - book_detail
    path('books/<int:id>/', views.book_detail, name='book_detail'),
    # книги - books
    path('books', views.books, name='books'),
    # редактирование книги - book_edit
    path('books/<int:id>/edit/', views.book_edit, name='book_edit'),
    # удаление книги - book_delete
    path('books/<int:id>/delete', views.book_delete, name='book_delete'),
    # создание книги - book_create
    path('book_create/', views.book_create, name='book_create'),
    # поиск книги - search_book
    path('search_book/', views.search_book, name='search_book'),
    # поиск избранной книги - search_favorite_book
    path('search_favorite_book/', views.search_favorite_book,
         name='search_favorite_book'),
    # рекомендации для книги - book_recommend
    path('book_recommend/<int:id>', views.book_recommend,
         name='book_recommend'),
    # рекомендации - recommendations
    path('recommendations', views.recommendations, name='recommendations'),

    # избранные книги - favorites
    path('favorites/', views.favorites, name='favorites'),
    # добавление книги в избранное - make_favore
    path('make_favore/<int:id>/', views.make_favore, name='make_favore'),
    # удаление книги из избранное - make_not_favore
    path('make_not_favore/<int:id>/', views.make_not_favore,
         name='make_not_favore'),

    # добавление комментария - add_comment
    path('books/<int:id>/comment/', views.add_comment, name='add_comment'),
    # удаление комментария - delete_comment
    path('books/<int:id>/comment/<int:comment_id>/delete',
         views.delete_comment, name='delete_comment'),

    # автор - author_detail
    path('/authors/<int:id>/', views.author_detail, name='author_detail'),
    # авторы - authors
    path('authors/', views.authors, name='authors'),
    # редактирование автора - author_edit
    path('/authors/<int:id>/edit/', views.author_edit, name='author_edit'),
    # добавление автора - author_create
    path('author_create/', views.author_create, name='author_create'),
    # удаление автора - author_delete
    path('/authors/<int:id>/delete', views.author_delete, name='author_delete'),
    # поиск автора - search_author
    path('search_author/', views.search_author, name='search_author'),

    # объект не найден - object_not_found
    path('object_not_found/', views.object_not_found, name='object_not_found'),

    path('section_create/', views.section_create, name='section_create'),
]

book_website/templates/authors/author_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
<link rel="stylesheet" href="{% static 'css/styles_bootstrap.css' %}">
{% block title %}
  "Детали"
{% endblock %}

{% block content %}
  <section class="a">
    <div class="container-fluid" style="background: rgba(225,180,148,0.65)">
      <div class="row">
        <div class="col-sm-1 col-lg-1"><p></p></div>

        <div class="col-sm-12 col-lg-12">
          <p id="author_name">{{ author.author_name }}</p>
        </div>

        <div class="col-sm-4 col-lg-4 shadow-sm">
          <div class="col">
            <div class="card h-100" >
              {% if author.author_photo %}
                <img src="{{ author.author_photo }}" class="card-img-top" alt="...">
              {% else %}
                {% thumbnail author.photo "960x339" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
              {% endif %}
            </div>
          </div>
        </div>

        <div class="col-sm-8 col-lg-8" id="book_description">
          <p style="background: white">Книги:</p>
          {% for book in book_list %}
            <a id="book_link"
             href="{% url 'books:book_detail' book.id %}">{{ book.name }}</a>
            <hr>
          {% endfor %}
        {% if user.username == 'dianaverevkina' %}
          <a class="btn btn-primary" style="background: #c79577; border-color: #8a5834"
             href="{% url 'books:author_edit' id=author.id %}">
          редактировать запись
          <a class="btn btn-primary"
             href="{% url 'books:author_delete' id=author.id %}" style="background: darkred">
            удалить запись
          </a>
        {% else %}
          <span style='color: darkred'> редактирование недоступно </span>
        {% endif %}
        </div>

        <div class="col-sm-12 col-lg-12">
          <p></p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

book_website/templates/authors/authors.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  "Авторы"
{% endblock %}

{% block content %}
  <section class="a" style="background: rgba(225,180,148,0.65)">
    <div class="container-fluid">
      <div class="row">
        <p></p>

        <form action="{% url 'books:search_author'%}" method="get">
          <input name="q" type="text" placeholder="Поиск...">
          <button type="submit" class="btn btn-primary"
                style="background: #72513e; border-color: #41220c">
          Найти
        </button>
        </form>

        {% include "includes/author_objects.html" %}
      </div>
      {% include 'includes/paginator.html' %}
      <p style="color: rgba(225,180,148,0.65)">-</p>
  </section>
{% endblock %}

book_website/templates/authors/create_author.html
{% extends "base.html" %}
{% block title %}
  Добавление автора
{% endblock %}

{% block content %}
  <div class="container-fluid" style="background: rgba(225,180,148,0.65)">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header"
                 style="background: #bd9379; color: white; font-weight: bold">
              {% if form.instance.pk %} Редактировать автора
              {% else %} Добавить автора {% endif %}
            </div>
            <div class="card-body" style="background: rgba(255,235,213,0.53)">
              {% include "includes/block_errors.html" %}
              <form method="post" enctype="multipart/form-data"
                      {% if form.instance.pk %}
                    action="{% url 'books:author_edit' form.instance.pk %}"
                      {% else %}
                    action="{% url 'books:author_create' %}" {% endif %}>
                {% csrf_token %}
                {% include "includes/form.html" %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary"
                          style="background: #72513e">
                    {% if form.instance.pk %} Сохранить
                    {% else %} Добавить {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}